"""empty message

Revision ID: 796d4afc3105
Revises: 8b83242eea10
Create Date: 2017-04-15 10:37:35.467132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796d4afc3105'
down_revision = '8b83242eea10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pin', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('pin', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pin', 'lng')
    op.drop_column('pin', 'lat')
    # ### end Alembic commands ###
